services:

  api:
    container_name: eStracta_api
    build: .
    ports:
      - 5000:5000
    depends_on:
      - postgres
    expose:
      - 5000

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: eStractaPassword
      POSTGRES_DB: eStracta
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    expose:
      - 5432